// Generated by scripts/generate_run_event_types.py. Do not edit by hand.

export const RUN_EVENT_SCHEMA_VERSION = 1 as const;

export interface RunModelUsage {
  model_turns?: number;
  tokens?: number;
  cost_usd?: number;
  [key: string]: unknown;
}

export interface RunEventEnvelope<TType extends string = string, TPayload = unknown> {
  sequence: number;
  event_id: string;
  schema_version: number;
  stream_epoch: string;
  run_id: string;
  session_id: string | null;
  step_id: string | null;
  attempt: number | null;
  trace_id: string;
  duration_ms?: number | null;
  model_usage?: RunModelUsage | null;
  redacted?: boolean;
  type: TType;
  payload: TPayload;
  created_at: string;
}

export type RunCreatedEvent = RunEventEnvelope<"run_created", { status: string; [key: string]: unknown }>;
export type StatusChangedEvent = RunEventEnvelope<"status_changed", { from: string; to: string; [key: string]: unknown }>;
export type StepStartedEvent = RunEventEnvelope<"step_started", { step_key: string; attempt: number; lease_epoch: number; [key: string]: unknown }>;
export type StepCommittedEvent = RunEventEnvelope<"step_committed", { step_key: string; attempt: number; lease_epoch: number; run_version: number; outcome: Record<string, unknown>; [key: string]: unknown }>;
export type InteractionRequestedEvent = RunEventEnvelope<"interaction_requested", { interaction_id: string; type: string; [key: string]: unknown }>;
export type InteractionResolvedEvent = RunEventEnvelope<"interaction_resolved", { interaction_id: string; run_version: number; status: string; [key: string]: unknown }>;

export type KnownRunEvent =
  | RunCreatedEvent
  | StatusChangedEvent
  | StepStartedEvent
  | StepCommittedEvent
  | InteractionRequestedEvent
  | InteractionResolvedEvent;

export type UnknownRunEvent = RunEventEnvelope<string, unknown>;
export type RunEvent = KnownRunEvent | UnknownRunEvent;

export const KNOWN_RUN_EVENT_TYPES = [
  "run_created",
  "status_changed",
  "step_started",
  "step_committed",
  "interaction_requested",
  "interaction_resolved",
] as const;

export type KnownRunEventType = typeof KNOWN_RUN_EVENT_TYPES[number];

export function isKnownRunEventType(value: string): value is KnownRunEventType {
  return (KNOWN_RUN_EVENT_TYPES as readonly string[]).includes(value);
}

export function isKnownRunEvent(event: RunEvent): event is KnownRunEvent {
  return event.schema_version === RUN_EVENT_SCHEMA_VERSION && isKnownRunEventType(event.type);
}
