"""Generate the frontend discriminated union from the Pydantic event registry."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backend.run_events import CORE_RUN_EVENT_MODELS

GENERATED_PATH = ROOT / "frontend" / "src" / "types" / "run-events.generated.ts"


def render_typescript() -> str:
    event_types = [str(model.model_fields["type"].default) for model in CORE_RUN_EVENT_MODELS]
    known_types = ",\n  ".join(f'"{event_type}"' for event_type in event_types)
    return f"""// Generated by scripts/generate_run_event_types.py. Do not edit by hand.

export const RUN_EVENT_SCHEMA_VERSION = 1 as const;

export interface RunModelUsage {{
  model_turns?: number;
  tokens?: number;
  cost_usd?: number;
  [key: string]: unknown;
}}

export interface RunEventEnvelope<TType extends string = string, TPayload = unknown> {{
  sequence: number;
  event_id: string;
  schema_version: number;
  stream_epoch: string;
  run_id: string;
  session_id: string | null;
  step_id: string | null;
  attempt: number | null;
  trace_id: string;
  duration_ms?: number | null;
  model_usage?: RunModelUsage | null;
  redacted?: boolean;
  type: TType;
  payload: TPayload;
  created_at: string;
}}

export type RunCreatedEvent = RunEventEnvelope<"run_created", {{ status: string; [key: string]: unknown }}>;
export type StatusChangedEvent = RunEventEnvelope<"status_changed", {{ from: string; to: string; [key: string]: unknown }}>;
export type StepStartedEvent = RunEventEnvelope<"step_started", {{ step_key: string; attempt: number; lease_epoch: number; [key: string]: unknown }}>;
export type StepCommittedEvent = RunEventEnvelope<"step_committed", {{ step_key: string; attempt: number; lease_epoch: number; run_version: number; outcome: Record<string, unknown>; [key: string]: unknown }}>;
export type InteractionRequestedEvent = RunEventEnvelope<"interaction_requested", {{ interaction_id: string; type: string; [key: string]: unknown }}>;
export type InteractionResolvedEvent = RunEventEnvelope<"interaction_resolved", {{ interaction_id: string; run_version: number; status: string; [key: string]: unknown }}>;

export type KnownRunEvent =
  | RunCreatedEvent
  | StatusChangedEvent
  | StepStartedEvent
  | StepCommittedEvent
  | InteractionRequestedEvent
  | InteractionResolvedEvent;

export type UnknownRunEvent = RunEventEnvelope<string, unknown>;
export type RunEvent = KnownRunEvent | UnknownRunEvent;

export const KNOWN_RUN_EVENT_TYPES = [
  {known_types},
] as const;

export type KnownRunEventType = typeof KNOWN_RUN_EVENT_TYPES[number];

export function isKnownRunEventType(value: string): value is KnownRunEventType {{
  return (KNOWN_RUN_EVENT_TYPES as readonly string[]).includes(value);
}}

export function isKnownRunEvent(event: RunEvent): event is KnownRunEvent {{
  return event.schema_version === RUN_EVENT_SCHEMA_VERSION && isKnownRunEventType(event.type);
}}
"""


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail without writing when the generated TypeScript is out of date",
    )
    args = parser.parse_args(argv)
    rendered = render_typescript()
    if args.check:
        if not GENERATED_PATH.exists() or GENERATED_PATH.read_text(encoding="utf-8") != rendered:
            raise SystemExit("generated Run event types are out of date; run scripts/generate_run_event_types.py")
        return
    GENERATED_PATH.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_PATH.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
